# Site settings
title: Natasha Levey
description: "Natasha Levey's portfolio"
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Natasha Levey
user_description: "Natasha is an aspiring software engineer studying computer science and professional writing  at WPI. She is a nerd; she truly enjoys her classes, and (for the most part) excels in them. In her free time, she enjoys playing drums in WPI's pep band and adventuring with her friends. " 
user_title: Software Developer
email: nwlevey@wpi.edu
twitter_username: lorem_ipsum
github_username:  nlevey
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
